
## Challenge: Implement the Nearest Neighbor algorithm 

The Nearest Neighbor algorithm is extremely simple. So simple, in fact, that you should be able to build it yourself from scratch using the Python you already know. Code a Nearest Neighbors algorithm that works for two dimensional data. You can use either arrays or dataframes to do this. Test it against the SKLearn package on the music dataset from above to ensure that it's correct. The goal here is to confirm your understanding of the model and continue to practice your Python skills. We're just expecting a brute force method here. After doing this, look up "ball tree" methods to see a more performant algorithm design.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
%matplotlib inline

# calculating Euclidean distance
from math import sqrt

from random import seed
from random import randrange

# sklearn KNN package
from sklearn.neighbors import KNeighborsClassifier

In [5]:
# Test distance function
dataset = [[2.7810836,2.550537003,0],
[1.465489372,2.362125076,0],
[3.396561688,4.400293529,0],
[1.38807019,1.850220317,0],
[3.06407232,3.005305973,0],
[7.627531214,2.759262235,1],
[5.332441248,2.088626775,1],
[6.922596716,1.77106367,1],
[8.675418651,-0.242068655,1],
[7.673756466,3.508563011,1]]
row0 = dataset[0]


In [6]:
# Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax

minmax = dataset_minmax(dataset)

print(minmax)
    
    


[[1.38807019, 8.675418651], [-0.242068655, 4.400293529], [0, 1]]


In [7]:
# Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
            

norm_dataset = normalize_dataset(dataset, minmax)


In [8]:
# calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

for row in dataset:
    distance = euclidean_distance(row0, row)
    print(distance)

0.0
0.18503704615208447
0.40730441463760725
0.2435098266117125
0.10537688495436288
0.6665675949019336
0.3639718753994556
0.5925997143359077
1.008013229674161
0.7023924588303547


In [9]:
# Locate the most similar neighbors
import operator 
def get_KNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclidean_distance(testInstance, trainingSet[x])
        distances.append((trainingSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

neighbors = get_KNeighbors(dataset, dataset[0], 3)
for neighbor in neighbors:
    print(neighbor)

[0.1911550432170284, 0.6015484245552352, 0.0]
[0.22998792207749216, 0.6995091074953493, 0.0]
[0.010623779336795444, 0.5609630674606582, 0.0]


In [11]:
# Make a classification prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_KNeighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction

prediction = predict_classification(dataset, dataset[0], 3)
print('Real value was %d, predicted value is %d.' % (dataset[0][-1], prediction))

Real value was 0, predicted value is 0.


In [16]:
# kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)

In [20]:
# evaluate algorithm
n_folds = 5
num_neighbors = 5

# predict the label
label = predict_classification(dataset, row, num_neighbors)
print('Data=%s, Predicted: %s' % (row, label))

Data=[0.8625477853350042, 0.8079144877852557, 1.0], Predicted: 1.0


### Applying model to music dataframe

In [24]:
music = pd.DataFrame()

# Some data to play with.
music['duration'] = [184, 134, 243, 186, 122, 197, 294, 382, 102, 264, 
                     205, 110, 307, 110, 397, 153, 190, 192, 210, 403,
                     164, 198, 204, 253, 234, 190, 182, 401, 376, 102]
music['loudness'] = [18, 34, 43, 36, 22, 9, 29, 22, 10, 24, 
                     20, 10, 17, 51, 7, 13, 19, 12, 21, 22,
                     16, 18, 4, 23, 34, 19, 14, 11, 37, 42]

# We know whether the songs in our training data are jazz or not.
music['jazz'] = [ 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
                  0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
                  1, 1, 1, 1, 0, 0, 1, 1, 0, 0]

In [25]:
dataset = music.copy()

In [26]:
dataset = dataset.to_numpy()

In [27]:
# Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax

minmax = dataset_minmax(dataset)

print(minmax)

[[102, 403], [4, 51], [0, 1]]


In [28]:
row0 = dataset[0]
# calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

for row in dataset:
    distance = euclidean_distance(row0, row)
    print(distance)

0.0
52.49761899362675
64.07807737440318
18.110770276274835
62.12889826803627
15.811388300841896
110.54863183232979
198.04039991880444
82.38931969618392
80.22468448052632
21.095023109728988
74.43117626371358
123.00406497347964
81.02468759581859
213.283848427395
31.400636936215164
6.082762530298219
10.0
26.1725046566048
219.03652663425797
20.09975124224178
14.0
24.413111231467404
69.18092222571191
52.49761899362675
6.082762530298219
4.47213595499958
217.1128738697915
192.93781381574738
85.44003745317531


In [29]:
# Locate the most similar neighbors
import operator 
def get_KNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclidean_distance(testInstance, trainingSet[x])
        distances.append((trainingSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

neighbors = get_KNeighbors(dataset, dataset[0], 5)
for neighbor in neighbors:
    print(neighbor)

[184  18   1]
[182  14   1]
[190  19   0]
[190  19   0]
[192  12   1]


In [30]:
# Make a classification prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_KNeighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction

prediction = predict_classification(dataset, dataset[5], 5)
print('Real value was %d, predicted value is %d.' % (dataset[0][-1], prediction))

Real value was 1, predicted value is 1.


In [31]:
# kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)

In [32]:
# evaluate algorithm
n_folds = 5
num_neighbors = 5

# predict the label
label = predict_classification(dataset, row, num_neighbors)
print('Data=%s, Predicted: %s' % (row, label))

Data=[102  42   0], Predicted: 0
